version: '3'
services:
  backend-nginx:
    volumes:
    - ./:/var/www/
    build:
      context: ./docker/backend/nginx
    ports:
    - "8888:80"
    networks:
    - internal

  backend-php-fpm:
    volumes:
    - ./:/var/www/
    build:
      context: ./docker/backend/php-fpm
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
    - internal

  backend-php-cli:
    volumes:
    - ./:/var/www/
    build:
      context: ./docker/backend/php-cli
    tty: true


networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.220.0/28
